Repository CaffeineJo/pick-n-click, pull requests merged in 2025-03, with the labels that each got.

#9 Feat shop manage 페이지 생성 및 라우팅 추가 #4
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/app/shop-manage/columns.tsx
  src/app/shop-manage/layout.tsx
  src/app/shop-manage/orders/page.tsx
  src/app/shop-manage/page.tsx
  src/components/common/Spacer.tsx
  src/components/shop-manage/app-sidebar.tsx
  src/components/shop-manage/data-table.tsx
  src/components/shop-manage/nav-main.tsx
  src/components/shop-manage/nav-user.tsx
  src/components/shop-manage/site-header.tsx
  src/components/ui/avatar.tsx
  src/components/ui/badge.tsx
  src/components/ui/breadcrumb.tsx
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/components/ui/chart.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/drawer.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/select.tsx
  src/components/ui/separator.tsx
  src/components/ui/sheet.tsx
  src/components/ui/sidebar.tsx
  src/components/ui/skeleton.tsx
  src/components/ui/sonner.tsx
  src/components/ui/table.tsx
  src/components/ui/tabs.tsx
  src/components/ui/toggle-group.tsx
  src/components/ui/toggle.tsx
  src/components/ui/tooltip.tsx
  src/hooks/use-mobile.tsx
  src/lib/utils.ts
  tailwind.config.ts
Labels: Feature

#11 장바구니 추가 버튼 구현
  src/components/cart/AddCartButton.tsx
  src/store/cartStore.ts
  src/types/type.ts
Labels: Feature

#18 Feat/shop manage
  pnpm-lock.yaml
  src/api/itemsApi.ts
  src/api/sellersApi.ts
  src/app/cart/page.tsx
  src/app/detail/[item_id]/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/provider.tsx
  src/app/shop-manage/columns.tsx
  src/app/shop-manage/create/page.tsx
  src/app/shop-manage/layout.tsx
  src/app/shop-manage/page.tsx
  src/components/common/Spacer.tsx
  src/components/shop-manage/dialog-row-actions.tsx
  src/components/shop-manage/nav-main.tsx
  src/components/shop-manage/site-header.tsx
  src/components/ui/dialog.tsx
  src/hooks/mutate/use-delete-item.ts
  src/hooks/mutate/use-update-item.ts
  src/hooks/queries/use-items-by-seller-id.tsx
Labels: Feature

#20 style : 리뷰 모달창 ui
  src/app/mypage/page.tsx
  src/components/mypage/ReviewModal.tsx
  src/components/ui/textarea.tsx
Labels: Feature, Style

#19 feat: 상품 주문하기 버튼 구현
  src/components/cart/AddCartButton.tsx
  src/components/cart/CartTotal.tsx
  src/components/cart/OrderButton.tsx
  src/store/authStore.ts
  src/types/cartType.ts
Labels: Feature

#21 move:이름 변경
  next.config.js
  next.config.mjs
  src/app/shop-manage/columns.tsx
  src/app/shop-manage/create/page.tsx
  src/app/shop-manage/layout.tsx
  src/app/shop-manage/orders/page.tsx
  src/app/shop-manage/page.tsx
  src/components/common/ImageUpload.tsx
  src/components/shop-manage/AppSideBar.tsx
  src/components/shop-manage/DataTable.tsx
  src/components/shop-manage/DialogRow.tsx
  src/components/shop-manage/ItemAddForm.tsx
  src/components/shop-manage/NavMain.tsx
  src/components/shop-manage/NavUser.tsx
  src/components/shop-manage/SiteHeader.tsx
  src/hooks/mutate/useDeleteItem.ts
  src/hooks/mutate/useUpdateItem.ts
  src/hooks/queries/useItemsBySellerId.tsx
  tsconfig.json
Labels: Feature

#24 Feat/third register
  src/app/login/_components/LoginForm.tsx
  src/app/login/page.tsx
  src/app/register/_components/RegisterForm.tsx
  src/app/register/page.tsx
  src/components/AuthListener.tsx
  src/components/login/LoginForm.tsx
  src/components/register/RegisterForm.tsx
  src/store/authStore.ts
Labels: Feature

#23 Feat/my page
  pnpm-lock.yaml
  src/api/itemsApi.ts
  src/api/orderedItemsApi.ts
  src/api/sellersApi.ts
  src/api/usersApi.ts
  src/app/mypage/_components/Card.tsx
  src/app/mypage/_components/Profile.tsx
  src/app/mypage/_components/StoreButton.tsx
  src/app/mypage/_types/type.ts
  src/app/mypage/page.tsx
Labels: Feature

#32 Feat: 마이페이지 리뷰모달연결, 타입오류 수정
  src/api/orderedItemsApi.ts
  src/api/reviewsApi.ts
  src/api/sellersApi.ts
  src/api/usersApi.ts
  src/api/wishApi.ts
  src/app/mypage/_components/Card.tsx
  src/app/mypage/_components/Profile.tsx
  src/app/mypage/_components/StoreButton.tsx
  src/app/mypage/_types/type.ts
  src/app/mypage/page.tsx
  src/components/mypage/ReviewModal.tsx
Labels: Feature

#33 feat: 주문 관리 페이지 구현
  src/api/orderedItemsApi.ts
  src/api/sellersApi.ts
  src/api/usersApi.ts
  src/app/mypage/_components/Card.tsx
  src/app/mypage/_types/type.ts
  src/app/shop-manage/orders/page.tsx
  src/components/cart/CartColumnDef.tsx
  src/components/cart/CartDataTable.tsx
  src/components/cart/OrderButton.tsx
  src/components/shop-manage/order/OrderColumnDef.tsx
  src/components/shop-manage/order/OrderDataTable.tsx
  src/hooks/mutate/useUpdateStatus.ts
  src/hooks/queries/useGetCart.ts
  src/hooks/queries/useGetOrders.ts
  src/types/orderType.ts
  src/utils/translateOrderStatus.ts
Labels: Feature

#34 Feat/social login
  package.json
  pnpm-lock.yaml
  src/app/login/page.tsx
  src/components/login/GoogleLoginBtn.tsx
  src/components/login/LoginForm.tsx
  src/components/login/SocialLoginForm.tsx
Labels: Feature

#48 feat: 후기 모달창에 상품 정보 추가
  src/api/reviewsApi.ts
  src/components/mypage/Card.tsx
  src/components/mypage/ReviewModal.tsx
  src/components/shop-manage/order/OrderStatusButton.tsx
Labels: Feature

#57 fix: 리렌더링되지 않는 문제 수정
  src/app/mypage/page.tsx
  src/components/mypage/Card.tsx
  src/components/mypage/ReviewModal.tsx
Labels: Bug
